//! Integration tests with a fake toolkit and a temp-file SQLite database.

mod attempts;
mod changed_mounts;
mod converted;
mod dispatcher;
mod durability;
mod files;
mod followups;
mod fs_browse;
mod goal_change;
mod hung_share;
mod interrupted_placing;
mod libraries;
mod library_folders;
mod older_mounts;
mod output_clash;
mod polish;
mod problems;
mod regressions;
mod results;
mod scan;
mod settings;
mod startup;
mod stuck_checks;
mod support;
mod unmounted_shares;
mod user_folders;
mod web;
